# Global platform
platform :ios, '10.0'

# Project path (required when project is run from an external drive)
project 'TeleMed.xcodeproj'


abstract_target 'TeleMed' do
	use_frameworks!
	
	pod 'AFNetworking', '~> 2.7'
	pod 'AFNetworkActivityLogger', '~> 2.0'
	pod 'KeychainItemWrapper'
  pod 'AppAuth'
  pod 'JWTDecode'

	target 'Med2Med'

	target 'MyTeleMed'
end
